# Generated by Django 3.1 on 2020-09-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='user', upload_to='user', verbose_name='头像'),
        ),
    ]
