# Generated by Django 3.1 on 2020-09-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200916_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='content_en',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='content_ja',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='content_zh_hans',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='title_ja',
            field=models.CharField(max_length=50, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='title_zh_hans',
            field=models.CharField(max_length=50, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='reply',
            name='r_content_en',
            field=models.CharField(max_length=256, null=True, verbose_name='回复内容'),
        ),
        migrations.AddField(
            model_name='reply',
            name='r_content_ja',
            field=models.CharField(max_length=256, null=True, verbose_name='回复内容'),
        ),
        migrations.AddField(
            model_name='reply',
            name='r_content_zh_hans',
            field=models.CharField(max_length=256, null=True, verbose_name='回复内容'),
        ),
    ]
